const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

const query = new URLSearchParams(window.location.search);
const API_ORIGIN = (query.get("api") || (window.location.protocol === "file:" ? "http://127.0.0.1:8000" : window.location.origin)).replace(/\/$/, "");
const WS_ORIGIN = API_ORIGIN.replace(/^http/, "ws");

const SPEEDS = [0.25, 0.5, 0.6, 0.8, 1];
const SCORE_RING_LENGTH = 138.23;
const SOURCE_VIDEO_ID = "jrUsvBKemBU";
const SOURCE_POSE_PATH = `./assets/tutorial-${SOURCE_VIDEO_ID}-pose.json`;
const SOURCE_DURATION_SECONDS = 20.47;
const SOURCE_ASPECT_RATIO = 9 / 16;

const FOCUS_STEPS = [
  { id: "upper", title: "Upper body only", hint: "Follow the arms and shoulders. Legs are intentionally hidden.", overlay: "Upper body overlay" },
  { id: "lower", title: "Lower body only", hint: "Now follow the hips, knees, and feet. Arms are intentionally hidden.", overlay: "Lower body overlay" },
  { id: "full", title: "Put it together", hint: "Combine both patterns only after practicing each half separately.", overlay: "Full-body overlay" },
];

// COCO-17: nose, eyes, ears, shoulders, elbows, wrists, hips, knees, ankles.
const COCO_BONES = [
  [0, 1], [0, 2], [1, 3], [2, 4],
  [3, 5], [4, 6],
  [5, 6], [5, 7], [7, 9], [6, 8], [8, 10],
  [5, 11], [6, 12], [11, 12],
  [11, 13], [13, 15], [12, 14], [14, 16],
];

const SCORE_BONES = [
  { name: "left_upper_arm", label: "Left shoulder", pair: [5, 7] },
  { name: "left_forearm", label: "Left wrist", pair: [7, 9] },
  { name: "right_upper_arm", label: "Right shoulder", pair: [6, 8] },
  { name: "right_forearm", label: "Right wrist", pair: [8, 10] },
  { name: "left_thigh", label: "Left knee", pair: [11, 13] },
  { name: "left_shin", label: "Left ankle", pair: [13, 15] },
  { name: "right_thigh", label: "Right knee", pair: [12, 14] },
  { name: "right_shin", label: "Right ankle", pair: [14, 16] },
];

const JOINT_LABELS = [
  "Nose", "Left eye", "Right eye", "Left ear", "Right ear",
  "Left shoulder", "Right shoulder", "Left elbow", "Right elbow",
  "Left wrist", "Right wrist", "Left hip", "Right hip",
  "Left knee", "Right knee", "Left ankle", "Right ankle",
];

// COCO-17 landmarks sampled from the lower tutorial coach in the supplied Short.
// The matching local H.264/AAC source and dense 30 FPS track are generated by
// scripts/process_tutorial.py. These sampled frames only initialize state while
// the matching JSON loads; an unavailable track is never shown as source truth.
const REFERENCE_KEYFRAMES = [
  [[.4394,.3434],[.4571,.3315],[.4190,.3324],[.4830,.3437],[.3907,.3456],[.5459,.4145],[.3596,.4217],[.6459,.4810],[.2862,.5038],[.7015,.4985],[.2426,.5164],[.5405,.5918],[.4272,.5959],[.5351,.7428],[.4365,.7493],[.5312,.9075],[.4428,.9132]],
  [[.5524,.3387],[.5736,.3288],[.5341,.3256],[.5924,.3429],[.4936,.3347],[.6182,.4244],[.4111,.4114],[.6374,.5338],[.3249,.5146],[.6421,.6178],[.3248,.5956],[.5351,.6091],[.4076,.6053],[.5240,.7591],[.4068,.7589],[.5098,.9191],[.4337,.9218]],
  [[.4824,.3380],[.5026,.3273],[.4590,.3259],[.5238,.3445],[.4157,.3427],[.5613,.4231],[.3695,.4191],[.5649,.5200],[.3719,.5051],[.4760,.4687],[.4545,.4542],[.5403,.6018],[.4073,.6016],[.5494,.7548],[.4077,.7538],[.5472,.8986],[.4276,.8988]],
  [[.4935,.3655],[.5160,.3548],[.4736,.3539],[.5423,.3688],[.4437,.3664],[.5932,.4387],[.3918,.4326],[.6990,.4848],[.2738,.4668],[.7457,.4669],[.2277,.4504],[.5669,.6083],[.4467,.6080],[.5614,.7623],[.4742,.7604],[.5771,.9078],[.5038,.9069]],
  [[.4014,.5034],[.4190,.4881],[.3782,.4923],[.4703,.4798],[.3629,.4883],[.5517,.5170],[.3743,.5096],[.7028,.5768],[.2694,.5149],[.8446,.6326],[.2033,.4976],[.5736,.6557],[.4343,.6574],[.7109,.7811],[.3950,.7894],[.8465,.8966],[.3306,.9145]],
  [[.4702,.3877],[.4901,.3736],[.4444,.3748],[.5121,.3795],[.3963,.3816],[.5413,.4501],[.3381,.4454],[.6173,.5350],[.2630,.5137],[.6769,.5845],[.2975,.5299],[.5085,.6191],[.3661,.6237],[.5872,.7597],[.3723,.7714],[.6885,.9014],[.4051,.9193]],
  [[.5636,.3536],[.5777,.3421],[.5385,.3402],[.5823,.3562],[.4822,.3521],[.6014,.4349],[.4114,.4165],[.6417,.5166],[.3420,.4824],[.6888,.4344],[.4308,.3970],[.5543,.5996],[.4166,.5987],[.6214,.7541],[.4078,.7585],[.6906,.8982],[.4076,.9157]],
  [[.2832,.4007],[.3024,.3890],[.2732,.3907],[.3601,.3850],[.2931,.3891],[.4344,.4249],[.3073,.4346],[.4042,.4537],[.2565,.4945],[.2551,.4340],[.1934,.5149],[.4296,.6010],[.3454,.5991],[.3940,.7427],[.3522,.7355],[.3566,.9043],[.3538,.8974]],
  [[.6787,.5051],[.6809,.4984],[.6755,.4925],[.6602,.4763],[.6412,.4673],[.6105,.4893],[.5230,.4741],[.5693,.5488],[.4513,.5328],[.6404,.5568],[.5970,.5570],[.4553,.5918],[.4050,.5912],[.5200,.7163],[.5211,.7216],[.4935,.8850],[.5606,.9002]],
  [[.5548,.3823],[.5630,.3695],[.5379,.3678],[.5353,.3702],[.4869,.3670],[.5049,.4331],[.4151,.4177],[.4653,.5332],[.3358,.4968],[.5357,.5783],[.4393,.5411],[.4442,.6182],[.3935,.6210],[.5462,.7263],[.5358,.7349],[.4348,.9052],[.4582,.9287]],
  [[.3290,.3445],[.3442,.3303],[.3117,.3334],[.3877,.3279],[.3056,.3346],[.4612,.3843],[.3207,.3957],[.4830,.4795],[.3328,.5047],[.3614,.5320],[.3020,.5563],[.4678,.5761],[.3760,.5779],[.4557,.7267],[.3871,.7286],[.4703,.8956],[.4259,.8960]],
  [[.3166,.3262],[.3525,.3212],[.3213,.3203],[.3961,.3360],[.3290,.3203],[.3984,.3766],[.3043,.3455],[.4553,.4088],[.4278,.3989],[.4310,.3644],[.5786,.4044],[.4292,.5235],[.3843,.5127],[.4094,.6701],[.5699,.6398],[.4412,.8030],[.8154,.7483]],
  [[.5761,.3361],[.5967,.3258],[.5552,.3234],[.6155,.3400],[.5119,.3328],[.6530,.4196],[.4423,.4090],[.6865,.5191],[.3750,.4871],[.6843,.5903],[.4190,.5124],[.6006,.6083],[.4673,.6073],[.5929,.7584],[.4576,.7639],[.5687,.9168],[.4626,.9196]],
  [[.5663,.3563],[.5813,.3461],[.5465,.3440],[.5871,.3566],[.4970,.3526],[.6094,.4267],[.4214,.4159],[.6073,.4971],[.3075,.5124],[.5829,.4732],[.2979,.5684],[.5639,.6101],[.4321,.6078],[.6431,.7555],[.4461,.7495],[.7021,.8950],[.4551,.9055]],
  [[.5964,.3856],[.6170,.3726],[.5760,.3715],[.6435,.3726],[.5406,.3705],[.6792,.4301],[.4939,.4353],[.7422,.5179],[.4601,.5342],[.7541,.6008],[.4557,.6081],[.6686,.6101],[.5541,.6150],[.6857,.7399],[.6011,.7462],[.6898,.8896],[.6593,.8904]],
  [[.4568,.3725],[.4754,.3612],[.4391,.3603],[.5033,.3687],[.4134,.3660],[.5426,.4307],[.3823,.4259],[.6036,.5017],[.3201,.4990],[.6297,.5147],[.3383,.5073],[.5346,.6046],[.4247,.6056],[.5716,.7564],[.4319,.7582],[.6216,.9229],[.4353,.9255]],
  [[.5677,.3944],[.5918,.3848],[.5504,.3815],[.6102,.3954],[.5072,.3841],[.6536,.4516],[.4090,.4393],[.7733,.4788],[.2687,.4593],[.8003,.4819],[.3308,.4485],[.6243,.6208],[.4780,.6220],[.6590,.7625],[.5602,.7612],[.6500,.9194],[.5926,.9104]],
  [[.5552,.3666],[.5776,.3553],[.5374,.3542],[.6145,.3605],[.5113,.3575],[.6788,.4184],[.4520,.4154],[.7157,.4792],[.3862,.4900],[.5932,.4585],[.4831,.4870],[.6370,.6016],[.4846,.5995],[.6307,.7551],[.4764,.7483],[.6273,.9149],[.4893,.9052]],
  [[.6173,.3320],[.6167,.3203],[.5983,.3218],[.5936,.3203],[.5403,.3254],[.6074,.3895],[.4672,.3914],[.5709,.4882],[.4578,.4836],[.6499,.5172],[.5823,.4982],[.5569,.5900],[.4642,.5973],[.6080,.7355],[.4883,.7574],[.5008,.8710],[.4148,.9101]],
  [[.5064,.3572],[.5267,.3463],[.4885,.3452],[.5509,.3535],[.4567,.3506],[.6000,.4076],[.4133,.4145],[.6596,.4270],[.3776,.4934],[.6446,.3962],[.3935,.5516],[.5821,.5795],[.4639,.5808],[.5750,.7384],[.4773,.7332],[.5566,.8919],[.5007,.8901]],
  [[.5344,.3562],[.5417,.3462],[.5172,.3458],[.5278,.3474],[.4632,.3489],[.5166,.3953],[.4227,.3984],[.5099,.4404],[.4366,.4464],[.5335,.4261],[.5421,.4237],[.5074,.5848],[.4247,.5904],[.5785,.7512],[.4154,.7601],[.6191,.8799],[.3853,.8925]],
  [[.6431,.4164],[.6515,.4084],[.6323,.4049],[.6299,.4157],[.5813,.4027],[.6069,.4690],[.5049,.4361],[.5890,.5278],[.4166,.4235],[.6165,.5530],[.5156,.3774],[.5682,.6061],[.5102,.6027],[.6057,.7384],[.6218,.7426],[.5122,.9005],[.5685,.9083]],
  [[.4387,.3541],[.4523,.3396],[.4150,.3436],[.4806,.3427],[.3828,.3513],[.5587,.4105],[.3827,.4283],[.6442,.4994],[.3941,.5405],[.6157,.5909],[.4180,.6307],[.5878,.6139],[.4697,.6208],[.5953,.7638],[.4573,.7727],[.6016,.9122],[.4490,.9196]],
  [[.5203,.3498],[.5382,.3404],[.5055,.3367],[.5578,.3554],[.4782,.3463],[.6036,.4302],[.4019,.4079],[.6497,.5132],[.3063,.4790],[.6396,.4526],[.3674,.4335],[.5408,.5954],[.4132,.5881],[.5248,.7542],[.4095,.7452],[.5123,.9230],[.4180,.9192]],
];

const state = {
  mode: "demo",
  practicePlan: "steps",
  focus: "upper",
  audioEnabled: true,
  speedLocked: true,
  playing: false,
  analyzing: false,
  speedIndex: 0,
  phase: 0,
  currentCount: 1,
  completedLoops: 0,
  cleanLoops: 0,
  loopMinimum: 1,
  elapsedPlayingMs: 0,
  sessionStartedAt: null,
  lastFrameAt: performance.now(),
  lastObservationAt: 0,
  observationInFlight: false,
  lastChartAt: 0,
  sessionId: null,
  remoteSession: false,
  sessionRequest: null,
  socket: null,
  socketReady: false,
  socketReconnects: 0,
  cameraStream: null,
  cameraReady: false,
  serverPose: null,
  score: null,
  boneScores: {},
  latestReference: clonePose(REFERENCE_KEYFRAMES[0]),
  latestLive: null,
  timingOffset: null,
  chartScores: [],
  memories: [],
  policyVersion: 1,
  remoteCoaching: null,
  remoteLearning: null,
  lastSocketSentAt: 0,
  routineKeyframes: REFERENCE_KEYFRAMES,
  sourceDuration: SOURCE_DURATION_SECONDS,
  sourceMotionReady: false,
  sourceBeats: [],
  detectedBpm: 90,
  countPhase: 0,
  currentBeatIndex: -1,
  previousSourceTime: 0,
};

const elements = {
  referenceCanvas: $("#referenceCanvas"),
  referenceVideo: $("#referenceVideo"),
  liveCanvas: $("#liveCanvas"),
  captureCanvas: $("#captureCanvas"),
  cameraVideo: $("#cameraVideo"),
  playButton: $("#playButton"),
  analyzeButton: $("#analyzeButton"),
  routineUrl: $("#routineUrl"),
  routineName: $("#routineName"),
  routineBpm: $("#routineBpm"),
  referenceLoading: $("#referenceLoading"),
  cameraEmpty: $("#cameraEmpty"),
  cameraError: $("#cameraError"),
  cameraErrorText: $("#cameraErrorText"),
  demoModeButton: $("#demoModeButton"),
  cameraModeButton: $("#cameraModeButton"),
  enableCameraButton: $("#enableCameraButton"),
  useDemoFallbackButton: $("#useDemoFallbackButton"),
  connectionDot: $("#connectionDot"),
  connectionLabel: $("#connectionLabel"),
  sessionClock: $("#sessionClock"),
  statusBanner: $("#statusBanner"),
  statusBannerText: $("#statusBannerText"),
  stageScore: $("#stageScore"),
  scoreRing: $("#scoreRing"),
  latencyLabel: $("#latencyLabel"),
  livePanelTitle: $("#livePanelTitle"),
  liveBadge: $("#liveBadge"),
  watermarkCount: $("#watermarkCount"),
  timelineFill: $("#timelineFill"),
  transportTitle: $("#transportTitle"),
  transportHint: $("#transportHint"),
  cleanLoops: $("#cleanLoops"),
  accuracyMetric: $("#accuracyMetric"),
  accuracyDelta: $("#accuracyDelta"),
  timingMetric: $("#timingMetric"),
  timingDelta: $("#timingDelta"),
  attentionMetric: $("#attentionMetric"),
  attentionDelta: $("#attentionDelta"),
  agentStateText: $("#agentStateText"),
  coachMessage: $("#coachMessage"),
  coachCue: $("#coachCue"),
  messageConfidence: $("#messageConfidence"),
  memoryEmpty: $("#memoryEmpty"),
  memoryList: $("#memoryList"),
  memoryCount: $("#memoryCount"),
  policyVersion: $("#policyVersion"),
  policyStatus: $("#policyStatus"),
  policyRule: $("#policyRule"),
  learningStepNumber: $("#learningStepNumber"),
  learningStepTitle: $("#learningStepTitle"),
  learningStepHint: $("#learningStepHint"),
  nextFocusButton: $("#nextFocusButton"),
  practicePlanHint: $("#practicePlanHint"),
  stepPlanButton: $("#stepPlanButton"),
  fullPlanButton: $("#fullPlanButton"),
  audioToggle: $("#audioToggle"),
  sourceOverlayLabel: $("#sourceOverlayLabel"),
  sourceBadge: $("#sourceBadge"),
  focusLabel: $("#focusLabel"),
  chartLine: $("#chartLine"),
  chartArea: $("#chartArea"),
  privacyDialog: $("#privacyDialog"),
  toastRegion: $("#toastRegion"),
};

function clonePose(pose) {
  return pose.map(([x, y]) => [x, y]);
}

function clamp(value, min = 0, max = 1) {
  return Math.max(min, Math.min(max, value));
}

function lerp(a, b, t) {
  return a + (b - a) * t;
}

function smoothstep(t) {
  return t * t * (3 - 2 * t);
}

function formatTime(milliseconds) {
  const total = Math.floor(milliseconds / 1000);
  return `${String(Math.floor(total / 60)).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}`;
}

function formatPlaybackSpeed(speed) {
  return `${Number(speed).toFixed(speed < .5 ? 2 : 1)}×`;
}

function getReferencePose(phase) {
  const keyframes = state.routineKeyframes;
  const position = phase * keyframes.length;
  const index = Math.floor(position) % keyframes.length;
  const nextIndex = (index + 1) % keyframes.length;
  const amount = smoothstep(position - Math.floor(position));
  return keyframes[index].map(([x, y], joint) => [
    lerp(x, keyframes[nextIndex][joint][0], amount),
    lerp(y, keyframes[nextIndex][joint][1], amount),
  ]);
}

async function loadSourceMotion() {
  try {
    const response = await fetch(SOURCE_POSE_PATH);
    if (!response.ok) throw new Error(`Pose track failed (${response.status})`);
    const payload = await response.json();
    const poses = payload.poses?.filter((pose) => Array.isArray(pose) && pose.length >= 17);
    if (!poses || poses.length < 8) throw new Error("Pose track is incomplete");
    state.routineKeyframes = poses;
    state.sourceDuration = Number(payload.duration) || SOURCE_DURATION_SECONDS;
    state.sourceBeats = Array.isArray(payload.beats) ? payload.beats.map(Number).filter(Number.isFinite) : [];
    state.detectedBpm = Number(payload.detected_bpm) || 90;
    elements.routineBpm.textContent = String(Math.round(state.detectedBpm));
    state.sourceMotionReady = true;
    elements.sourceBadge.innerHTML = "<i></i> ML track ready";
  } catch {
    state.sourceMotionReady = false;
    elements.sourceBadge.innerHTML = "<i></i> ML track unavailable";
    showBanner("The local pose track could not load, so scoring and the coach overlay are paused instead of showing mismatched motion.");
  }
}

function updateFocusUI() {
  const index = Math.max(0, FOCUS_STEPS.findIndex((step) => step.id === state.focus));
  const step = FOCUS_STEPS[index];
  const stepByStep = state.practicePlan === "steps";
  elements.learningStepNumber.textContent = stepByStep ? `Step ${index + 1} of ${FOCUS_STEPS.length}` : "Full routine";
  elements.learningStepTitle.textContent = stepByStep ? step.title : "Everything together";
  elements.learningStepHint.textContent = stepByStep ? step.hint : "Follow the complete coach motion with the video, audio, and beat counts synchronized.";
  elements.sourceOverlayLabel.textContent = step.overlay;
  elements.focusLabel.textContent = `Focus · ${step.id === "full" ? "full body" : `${step.id} body only`}`;
  elements.practicePlanHint.textContent = stepByStep
    ? "Learn upper body, then lower body, then combine"
    : "Practice the complete movement from the start";
  elements.stepPlanButton.classList.toggle("active", stepByStep);
  elements.stepPlanButton.setAttribute("aria-pressed", String(stepByStep));
  elements.fullPlanButton.classList.toggle("active", !stepByStep);
  elements.fullPlanButton.setAttribute("aria-pressed", String(!stepByStep));
  $("#focusSteps").hidden = !stepByStep;
  elements.nextFocusButton.hidden = !stepByStep;
  elements.nextFocusButton.textContent = index === FOCUS_STEPS.length - 1
    ? "Restart: upper body"
    : `Next: ${FOCUS_STEPS[index + 1].id} body`;
  elements.nextFocusButton.classList.toggle("complete", index === FOCUS_STEPS.length - 1);
  $$(".focus-step").forEach((button) => {
    const active = button.dataset.focus === state.focus;
    button.classList.toggle("active", active);
    button.setAttribute("aria-pressed", String(active));
  });
}

function setPracticePlan(plan, { announce = true } = {}) {
  if (!["steps", "full"].includes(plan)) return;
  const changed = state.practicePlan !== plan;
  if (!changed) return;
  state.practicePlan = plan;
  setFocus(plan === "steps" ? "upper" : "full", { announce: false });
  if (announce && changed) {
    toast(plan === "steps"
      ? "Step-by-step plan · start with upper body only"
      : "Full routine plan · complete movement enabled");
  }
}

function setFocus(focus, { announce = true } = {}) {
  if (!FOCUS_STEPS.some((step) => step.id === focus)) return;
  const changed = state.focus !== focus;
  pausePractice();
  state.focus = focus;
  state.phase = 0;
  state.currentCount = 1;
  state.countPhase = 0;
  state.currentBeatIndex = -1;
  state.previousSourceTime = 0;
  state.score = null;
  state.boneScores = {};
  state.cleanLoops = 0;
  state.completedLoops = 0;
  state.loopMinimum = 1;
  elements.cleanLoops.textContent = "0";
  if (changed) {
    state.sessionId = null;
    state.remoteSession = false;
    state.remoteCoaching = null;
    state.remoteLearning = null;
    state.memories = [];
    renderMemories();
  }
  elements.referenceVideo.currentTime = 0;
  elements.attentionMetric.textContent = focus === "upper" ? "Arms + shoulders" : focus === "lower" ? "Hips + legs" : "Whole body";
  elements.attentionDelta.textContent = "Only this learning step is scored";
  elements.coachMessage.textContent = focus === "upper"
    ? "First, copy only the coach’s arms and shoulders. Ignore the legs for this pass."
    : focus === "lower"
      ? "Now copy only the weight shifts, knees, and feet. Ignore the arms for this pass."
      : "Now combine the upper- and lower-body patterns into the complete move.";
  elements.messageConfidence.textContent = "one focus only";
  elements.coachCue.hidden = false;
  elements.policyRule.textContent = `Score only the ${focus === "full" ? "combined move" : `${focus} body`} in this step.`;
  updateFocusUI();
  updateCountUI();
  updateScoreUI();
  if (announce) toast(`${FOCUS_STEPS.find((step) => step.id === focus).title} · video reset to the start`);
}

function setAudioEnabled(enabled, { announce = true } = {}) {
  state.audioEnabled = Boolean(enabled);
  elements.referenceVideo.muted = !state.audioEnabled;
  elements.referenceVideo.volume = 1;
  elements.audioToggle.setAttribute("aria-pressed", String(state.audioEnabled));
  elements.audioToggle.querySelector("span").textContent = state.audioEnabled ? "Audio on" : "Audio muted";
  updateTimingUI();
  if (announce) toast(state.audioEnabled ? "Source audio on · beat counts synchronized" : "Source audio muted");
}

function createDemoPose(reference, timestamp) {
  const pose = clonePose(reference);
  const progress = clamp((state.elapsedPlayingMs - 900) / 6800);
  const error = lerp(0.105, 0.026, progress);
  const wave = Math.sin(timestamp / 370);
  const counterWave = Math.cos(timestamp / 490);

  // Stable, deterministic mistakes: the agent can visibly diagnose and reduce them.
  pose[8][0] -= error * 0.32;
  pose[8][1] += error * 0.22;
  pose[10][0] -= error * (0.95 + wave * 0.12);
  pose[10][1] += error * 0.55;
  pose[7][0] += error * 0.18;
  pose[9][0] += error * (0.55 + counterWave * 0.1);
  pose[13][0] += error * 0.42;
  pose[15][0] += error * 0.58;
  pose[14][1] += error * 0.16;
  pose[16][0] -= error * 0.18;

  const bodySway = Math.sin(timestamp / 720) * 0.008;
  return pose.map(([x, y]) => [clamp(x + bodySway, 0.04, 0.96), clamp(y, 0.04, 0.96)]);
}

function cosineSimilarity(a, b) {
  const dot = a[0] * b[0] + a[1] * b[1];
  const lengthA = Math.hypot(a[0], a[1]);
  const lengthB = Math.hypot(b[0], b[1]);
  if (lengthA < 0.0001 || lengthB < 0.0001) return 0;
  return clamp(dot / (lengthA * lengthB));
}

function boneMatchesFocus(bone, focus = state.focus) {
  const lowerBody = bone.name.includes("thigh") || bone.name.includes("shin");
  return focus === "full" || (focus === "lower" ? lowerBody : !lowerBody);
}

function calculatePoseScore(live, reference, demoPenalty = 0, focus = state.focus) {
  const boneScores = {};
  const focusedBones = SCORE_BONES.filter((bone) => boneMatchesFocus(bone, focus));
  for (const bone of focusedBones) {
    const [start, end] = bone.pair;
    if (!live[start] || !live[end] || !reference[start] || !reference[end]) {
      boneScores[bone.name] = 0;
      continue;
    }
    const liveVector = [live[end][0] - live[start][0], live[end][1] - live[start][1]];
    const refVector = [reference[end][0] - reference[start][0], reference[end][1] - reference[start][1]];
    boneScores[bone.name] = clamp(cosineSimilarity(liveVector, refVector) - demoPenalty);
  }
  return {
    score: Object.values(boneScores).reduce((sum, value) => sum + value, 0) / focusedBones.length,
    boneScores,
  };
}

function resizeCanvas(canvas) {
  const rect = canvas.getBoundingClientRect();
  if (!rect.width || !rect.height) return null;
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  const width = Math.round(rect.width * dpr);
  const height = Math.round(rect.height * dpr);
  if (canvas.width !== width || canvas.height !== height) {
    canvas.width = width;
    canvas.height = height;
  }
  const context = canvas.getContext("2d");
  context.setTransform(dpr, 0, 0, dpr, 0, 0);
  context.clearRect(0, 0, rect.width, rect.height);
  return { context, width: rect.width, height: rect.height };
}

function mappedPoint(point, width, height, sourceAspect = null) {
  if (sourceAspect) {
    const contentWidth = Math.min(width, height * sourceAspect);
    const contentHeight = Math.min(height, width / sourceAspect);
    return [
      (width - contentWidth) / 2 + point[0] * contentWidth,
      (height - contentHeight) / 2 + point[1] * contentHeight,
    ];
  }
  return [width * (0.07 + point[0] * 0.86), height * (0.035 + point[1] * 0.92)];
}

function jointMatchesFocus(index, focus) {
  if (focus === "upper") return index <= 12;
  if (focus === "lower") return index >= 11;
  return true;
}

function skeletonBoneMatchesFocus(pair, focus) {
  if (focus === "upper") return pair[0] <= 12 && pair[1] <= 12;
  if (focus === "lower") return pair[0] >= 11 && pair[1] >= 11;
  return true;
}

function colorForScore(score) {
  if (score == null) return "#b7ff5a";
  if (score >= 0.9) return "#b7ff5a";
  if (score >= 0.78) return "#ffd36b";
  return "#ff7d69";
}

function scoreForJoint(index, boneScores) {
  const relevant = SCORE_BONES.filter((bone) => bone.pair.includes(index));
  if (!relevant.length) return null;
  const values = relevant.map((bone) => boneScores[bone.name]).filter(Number.isFinite);
  return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
}

function scoreForBone(pair, boneScores) {
  const found = SCORE_BONES.find((bone) => bone.pair[0] === pair[0] && bone.pair[1] === pair[1]);
  return found ? boneScores[found.name] : null;
}

function renderSkeleton(canvas, pose, options = {}) {
  const resized = resizeCanvas(canvas);
  if (!resized || !pose?.length) return;
  const { context: ctx, width, height } = resized;
  const focus = options.focus || "full";
  const points = pose.map((point) => mappedPoint(point, width, height, options.sourceAspect));
  const primary = options.primary || "#b7ff5a";
  const boneScores = options.boneScores || {};

  if (options.trailPose) {
    const trailPoints = options.trailPose.map((point) => mappedPoint(point, width, height, options.sourceAspect));
    ctx.save();
    ctx.globalAlpha = 0.12;
    ctx.strokeStyle = primary;
    ctx.lineWidth = 2;
    for (const [start, end] of COCO_BONES) {
      if (!skeletonBoneMatchesFocus([start, end], focus)) continue;
      ctx.beginPath();
      ctx.moveTo(...trailPoints[start]);
      ctx.lineTo(...trailPoints[end]);
      ctx.stroke();
    }
    ctx.restore();
  }

  for (const pair of COCO_BONES) {
    if (!skeletonBoneMatchesFocus(pair, focus)) continue;
    const [start, end] = pair;
    if (!points[start] || !points[end]) continue;
    const score = scoreForBone(pair, boneScores);
    const color = options.feedback ? colorForScore(score) : primary;
    ctx.save();
    ctx.beginPath();
    ctx.moveTo(...points[start]);
    ctx.lineTo(...points[end]);
    ctx.lineCap = "round";
    ctx.lineWidth = options.feedback && score != null && score < 0.78 ? 5 : 3.4;
    ctx.strokeStyle = color;
    ctx.shadowBlur = options.feedback && score != null && score < 0.78 ? 14 : 9;
    ctx.shadowColor = color;
    ctx.stroke();
    ctx.restore();
  }

  points.forEach(([x, y], index) => {
    if (!jointMatchesFocus(index, focus)) return;
    const jointScore = scoreForJoint(index, boneScores);
    const color = options.feedback ? colorForScore(jointScore) : primary;
    if (options.feedback && jointScore != null && jointScore < 0.78) {
      ctx.beginPath();
      ctx.arc(x, y, 11, 0, Math.PI * 2);
      ctx.fillStyle = `${color}20`;
      ctx.fill();
    }
    ctx.beginPath();
    ctx.arc(x, y, index <= 4 ? 2.6 : 4.1, 0, Math.PI * 2);
    ctx.fillStyle = color;
    ctx.shadowBlur = 9;
    ctx.shadowColor = color;
    ctx.fill();
    ctx.shadowBlur = 0;
    ctx.beginPath();
    ctx.arc(x, y, index <= 4 ? 1 : 1.4, 0, Math.PI * 2);
    ctx.fillStyle = "rgba(255,255,255,.9)";
    ctx.fill();
  });

  // A subtle center-of-mass guide makes the pose output feel analytical.
  if (focus !== "full") return;
  const hipCenter = [(points[11][0] + points[12][0]) / 2, (points[11][1] + points[12][1]) / 2];
  ctx.save();
  ctx.setLineDash([2, 5]);
  ctx.strokeStyle = options.feedback ? "rgba(183,255,90,.18)" : "rgba(159,131,255,.18)";
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(hipCenter[0], hipCenter[1]);
  ctx.lineTo(hipCenter[0], height * .88);
  ctx.stroke();
  ctx.restore();
}

function clearCanvas(canvas) {
  const resized = resizeCanvas(canvas);
  if (!resized) return;
}

function updateScoreUI() {
  if (!Number.isFinite(state.score)) {
    elements.stageScore.textContent = "--";
    elements.accuracyMetric.textContent = "--";
    elements.scoreRing.style.strokeDashoffset = SCORE_RING_LENGTH;
    return;
  }
  const percent = Math.round(state.score * 100);
  elements.stageScore.textContent = percent;
  elements.accuracyMetric.textContent = `${percent}%`;
  elements.scoreRing.style.strokeDashoffset = SCORE_RING_LENGTH * (1 - state.score);
  elements.scoreRing.style.stroke = colorForScore(state.score);
  elements.accuracyDelta.textContent = percent >= 90 ? "Mastery range" : percent >= 85 ? "Building consistency" : "One correction at a time";

  const weakest = SCORE_BONES
    .map((bone) => ({ ...bone, score: state.boneScores[bone.name] }))
    .filter((bone) => Number.isFinite(bone.score))
    .sort((a, b) => a.score - b.score)[0];
  const remoteWeakest = state.remoteSession ? state.remoteLearning?.weakest : null;
  if (remoteWeakest) {
    elements.attentionMetric.textContent = remoteWeakest.label;
    elements.attentionDelta.textContent = remoteWeakest.detail;
  } else if (weakest) {
    elements.attentionMetric.textContent = weakest.label;
    elements.attentionDelta.textContent = `${Math.round(weakest.score * 100)}% aligned · active cue`;
  }
}

function updateTimingUI() {
  state.timingOffset = null;
  elements.timingMetric.textContent = state.playing ? `Count ${state.currentCount}` : "Ready";
  const practiceBpm = Math.round(state.detectedBpm * SPEEDS[state.speedIndex]);
  elements.timingDelta.textContent = `${practiceBpm} BPM practice · ${state.audioEnabled ? "audio on" : "audio muted"}`;
}

function updateCountUI() {
  elements.watermarkCount.textContent = state.currentCount;
  elements.timelineFill.style.width = `${state.countPhase * 100}%`;
  $$(".count-marker").forEach((marker, index) => {
    marker.classList.toggle("active", index + 1 === state.currentCount);
    marker.classList.toggle("done", index + 1 < state.currentCount);
  });
}

function setAgentStep(step) {
  const mapping = {
    observe: ["#stepObserve", "Observing"],
    diagnose: ["#stepDiagnose", "Diagnosing"],
    adapt: ["#stepAdapt", "Adapting policy"],
  };
  ["#stepObserve", "#stepDiagnose", "#stepAdapt"].forEach((id) => $(id).classList.remove("active"));
  $(mapping[step][0]).classList.add("active");
  elements.agentStateText.textContent = mapping[step][1];
}

function updateAgentUI() {
  if (!state.playing) {
    setAgentStep("observe");
    elements.agentStateText.textContent = state.score == null ? "Ready to observe" : "Paused safely";
    return;
  }
  const cycle = state.countPhase % 1;
  if (cycle < .52) setAgentStep("observe");
  else if (cycle < .83) setAgentStep("diagnose");
  else setAgentStep("adapt");

  const elapsed = state.elapsedPlayingMs;
  if (state.remoteSession && state.remoteCoaching) {
    elements.coachMessage.textContent = state.remoteCoaching;
    elements.messageConfidence.textContent = "server policy";
  } else if (state.remoteSession) {
    elements.coachMessage.textContent = `Evaluating only your ${state.focus === "full" ? "combined movement" : `${state.focus} body`} in this step.`;
    elements.messageConfidence.textContent = "agent evaluating";
  } else if (elapsed < 900) {
    elements.coachMessage.textContent = state.focus === "upper"
      ? "Watch only the purple arm and shoulder lines over the coach. Ignore the legs."
      : state.focus === "lower"
        ? "Watch only the purple hip, knee, and ankle lines. Ignore the arms."
        : "Combine the two patterns now; keep the same timing as the source audio.";
    elements.messageConfidence.textContent = "one focus only";
  } else {
    const weakest = SCORE_BONES
      .filter((bone) => boneMatchesFocus(bone))
      .map((bone) => ({ ...bone, score: state.boneScores[bone.name] }))
      .filter((bone) => Number.isFinite(bone.score))
      .sort((a, b) => a.score - b.score)[0];
    elements.coachMessage.textContent = weakest
      ? `One change: match the coach’s ${weakest.label.toLowerCase()} path. Keep everything else unchanged.`
      : `Keep following only the ${state.focus === "full" ? "combined move" : `${state.focus}-body pattern`}.`;
    elements.messageConfidence.textContent = "single active cue";
  }
  elements.coachCue.hidden = false;

  if (!state.remoteSession) {
    const desiredMemories = [];
    if (elapsed >= 1100) desiredMemories.push({ title: `${FOCUS_STEPS.find((step) => step.id === state.focus).title} active`, detail: "Other body regions excluded from scoring", score: "isolated" });
    if (elapsed >= 3200) desiredMemories.push({ title: "Source-synced coach path", detail: "YOLO landmarks follow the local tutorial video", score: "ML" });
    if (elapsed >= 5900) desiredMemories.push({ title: "Audio timing available", detail: "Video and pose track share one clock", score: "synced" });
    if (desiredMemories.length !== state.memories.length) {
      state.memories = desiredMemories;
      renderMemories();
    }
  }

  if (state.remoteSession && state.remoteLearning?.policy) {
    elements.policyRule.textContent = state.remoteLearning.policy;
    elements.policyStatus.textContent = "Server applied";
  } else if (state.remoteSession) {
    elements.policyRule.textContent = "Waiting for enough live evidence to revise the coaching policy.";
    elements.policyStatus.textContent = "Evaluating";
  } else if (elapsed < 2500) {
    elements.policyRule.innerHTML = `<b>Step ${FOCUS_STEPS.findIndex((step) => step.id === state.focus) + 1}:</b> score ${state.focus === "full" ? "the combined move" : `${state.focus} body only`}.`;
    elements.policyStatus.textContent = "Learning";
  } else if (elapsed < 6500) {
    elements.policyRule.innerHTML = "<b>Updated:</b> show one weakest joint cue at a time.";
    elements.policyStatus.textContent = "Applied";
  } else {
    elements.policyRule.innerHTML = "<b>Updated:</b> retain this body focus until you choose the next step.";
    elements.policyStatus.textContent = "Applied";
  }
}

function renderMemories() {
  const remoteCount = state.remoteSession ? Number(state.remoteLearning?.memoryCount) : NaN;
  elements.memoryCount.textContent = Number.isFinite(remoteCount)
    ? `${remoteCount} signal${remoteCount === 1 ? "" : "s"}`
    : `${state.memories.length} signal${state.memories.length === 1 ? "" : "s"}`;
  elements.memoryEmpty.hidden = state.memories.length > 0;
  elements.memoryList.hidden = state.memories.length === 0;
  elements.memoryList.replaceChildren();
  state.memories.forEach((memory) => {
    const item = document.createElement("div");
    item.className = "memory-item";
    const dot = document.createElement("i");
    const copy = document.createElement("div");
    const title = document.createElement("strong");
    const detail = document.createElement("small");
    const score = document.createElement("span");
    title.textContent = memory.title;
    detail.textContent = memory.detail;
    score.textContent = memory.score;
    copy.append(title, detail);
    item.append(dot, copy, score);
    elements.memoryList.append(item);
  });
}

function updateChart(now) {
  if (!state.playing || !Number.isFinite(state.score) || now - state.lastChartAt < 420) return;
  state.lastChartAt = now;
  state.chartScores.push(state.score);
  if (state.chartScores.length > 28) state.chartScores.shift();
  const values = state.chartScores;
  if (values.length < 2) return;
  const points = values.map((value, index) => {
    const x = (index / (values.length - 1)) * 280;
    const y = 58 - clamp((value - .55) / .45) * 51;
    return [x, y];
  });
  const path = points.map(([x, y], index) => `${index ? "L" : "M"}${x.toFixed(1)},${y.toFixed(1)}`).join(" ");
  elements.chartLine.setAttribute("d", path);
  elements.chartArea.setAttribute("d", `${path} L280,64 L0,64 Z`);
}

function handleCompletedLoop() {
  state.completedLoops += 1;
  const passed = state.loopMinimum >= .85;
  state.cleanLoops = passed ? Math.min(2, state.cleanLoops + 1) : 0;
  state.loopMinimum = 1;
  elements.cleanLoops.textContent = state.cleanLoops;

  if (passed) {
    toast(`Clean loop ${state.cleanLoops}/2 · minimum frame score held above 85%`);
  } else {
    elements.transportHint.textContent = "The coach isolated one cue; repeat without adding new changes.";
  }

  if (state.cleanLoops >= 2 && state.speedIndex < SPEEDS.length - 1) {
    const previous = state.speedIndex;
    state.speedIndex += 1;
    state.cleanLoops = 0;
    state.policyVersion += 1;
    elements.cleanLoops.textContent = "0";
    elements.policyVersion.textContent = `Policy v1.${state.policyVersion - 1}`;
    updateSpeedUI(previous);
    toast(`Mastery unlocked · coach speed is now ${formatPlaybackSpeed(SPEEDS[state.speedIndex])}`);
  }
}

function updateSpeedUI(previousIndex = null) {
  elements.referenceVideo.playbackRate = SPEEDS[state.speedIndex];
  $$(".speed-tier").forEach((button, index) => {
    button.classList.toggle("active", index === state.speedIndex);
    if (previousIndex != null && index <= previousIndex) button.classList.add("passed");
  });
}

function normalizeScore(value) {
  if (value == null || value === "") return null;
  const number = Number(value);
  if (!Number.isFinite(number)) return null;
  return clamp(number > 1 ? number / 100 : number);
}

function normalizeBoneScores(payload) {
  const source = payload?.bone_scores ?? payload?.joint_scores ?? payload?.scores?.bones ?? payload?.pose?.bone_scores;
  if (!source) return {};
  if (Array.isArray(source)) {
    const normalized = {};
    source.forEach((entry, index) => {
      if (entry && typeof entry === "object") {
        const rawName = String(entry.name ?? entry.bone ?? entry.segment ?? SCORE_BONES[index]?.name ?? "")
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, "_")
          .replace(/^_|_$/g, "");
        const matched = SCORE_BONES.find((bone) => bone.name === rawName)
          ?? SCORE_BONES.find((bone) => rawName.includes(bone.name))
          ?? SCORE_BONES[index];
        const value = normalizeScore(entry.similarity ?? entry.score ?? entry.value ?? entry.accuracy);
        if (matched && value != null) normalized[matched.name] = value;
      } else if (SCORE_BONES[index]) {
        normalized[SCORE_BONES[index].name] = normalizeScore(entry) ?? 0;
      }
    });
    return normalized;
  }
  const normalized = {};
  for (const bone of SCORE_BONES) {
    const value = source[bone.name] ?? source[bone.label] ?? source[bone.name.replaceAll("_", " ")];
    if (value != null) normalized[bone.name] = normalizeScore(value);
  }
  return normalized;
}

function normalizePose(raw, payload = {}) {
  if (!raw) return null;
  const points = Array.isArray(raw) ? raw : raw.keypoints ?? raw.points ?? raw.xy;
  if (!Array.isArray(points) || points.length < 17) return null;
  const parsed = points.slice(0, 17).map((point) => {
    if (Array.isArray(point)) return [Number(point[0]), Number(point[1])];
    return [Number(point.x), Number(point.y)];
  });
  if (parsed.some(([x, y]) => !Number.isFinite(x) || !Number.isFinite(y))) return null;
  const maxCoordinate = Math.max(...parsed.flat().map(Math.abs));
  if (maxCoordinate <= 2) return parsed.map(([x, y]) => [clamp(x), clamp(y)]);
  const width = Number(payload.width ?? payload.image_width ?? payload.frame_width ?? elements.cameraVideo.videoWidth ?? 1);
  const height = Number(payload.height ?? payload.image_height ?? payload.frame_height ?? elements.cameraVideo.videoHeight ?? 1);
  return parsed.map(([x, y]) => [clamp(x / width), clamp(y / height)]);
}

function extractCoaching(payload) {
  const candidate = payload?.coaching ?? payload?.coach_message ?? payload?.feedback ?? payload?.agent?.message ?? payload?.observation?.coaching;
  if (typeof candidate === "string") return candidate;
  if (candidate && typeof candidate === "object") return candidate.message ?? candidate.text ?? candidate.next_best_action ?? null;
  return null;
}

function applyBackendPayload(payload, source = "api") {
  if (!payload || typeof payload !== "object") return;
  const nested = payload.data ?? payload.result ?? payload.observation ?? payload;
  const backendState = nested.state && typeof nested.state === "object" ? nested.state : {};
  const pose = normalizePose(
    nested.user_keypoints ?? nested.keypoints ?? nested.pose?.keypoints ?? nested.pose,
    nested,
  );
  if (pose) {
    // The camera preview is mirrored, so its pose overlay must mirror as well.
    state.serverPose = pose.map(([x, y]) => [1 - x, y]);
  }

  const backendScore = normalizeScore(nested.score ?? nested.accuracy ?? nested.frame_score ?? nested.pose_score);
  const backendBones = normalizeBoneScores(nested);
  if (backendScore != null) state.score = backendScore;
  if (Object.keys(backendBones).length) state.boneScores = backendBones;
  const coaching = extractCoaching(nested);
  if (coaching) state.remoteCoaching = coaching;

  const speedValue = nested.speed
    ?? nested.current_speed
    ?? nested.playback_speed
    ?? nested.speed_tier
    ?? nested.mastery?.speed
    ?? nested.policy?.speed
    ?? backendState.speed;
  const parsedSpeed = Number.parseFloat(String(speedValue ?? "").replace("×", ""));
  const remoteSpeedIndex = SPEEDS.findIndex((speed) => Math.abs(speed - parsedSpeed) < .001);
  if (remoteSpeedIndex >= 0 && remoteSpeedIndex !== state.speedIndex && !state.speedLocked) {
    const previous = state.speedIndex;
    state.speedIndex = remoteSpeedIndex;
    updateSpeedUI(remoteSpeedIndex > previous ? previous : null);
    toast(`Agent policy set coach speed to ${formatPlaybackSpeed(SPEEDS[remoteSpeedIndex])}`);
  }

  const remoteCleanLoops = Number(
    nested.clean_loops
    ?? nested.mastery_streak
    ?? nested.mastery?.clean_loops
    ?? nested.mastery?.streak
    ?? backendState.qualifying_streak
    ?? backendState.clean_loops,
  );
  if (Number.isFinite(remoteCleanLoops)) {
    state.cleanLoops = clamp(Math.round(remoteCleanLoops), 0, 2);
    elements.cleanLoops.textContent = state.cleanLoops;
  }

  const policy = nested.policy ?? nested.agent?.policy ?? nested.coaching_policy ?? backendState.policy;
  const version = nested.policy_version ?? nested.agent?.policy_version ?? policy?.version;
  if (version != null) elements.policyVersion.textContent = String(version).startsWith("v") ? `Policy ${version}` : `Policy v${version}`;
  const policyRule = typeof policy === "string" ? policy : policy?.rule ?? policy?.description ?? policy?.change;
  if (policyRule) {
    state.remoteLearning = { ...(state.remoteLearning || {}), policy: String(policyRule) };
    elements.policyRule.textContent = policyRule;
    elements.policyStatus.textContent = "Server applied";
  }

  const weakestRaw = nested.weakest_bone
    ?? nested.weakest_joint
    ?? nested.diagnosis?.weakest_bone
    ?? nested.agent?.weakest_bone
    ?? backendState.weakest_bone;
  let normalizedWeakest = null;
  if (weakestRaw) {
    const rawName = typeof weakestRaw === "string"
      ? weakestRaw
      : weakestRaw.name ?? weakestRaw.bone ?? weakestRaw.joint ?? weakestRaw.label;
    if (rawName) {
      const label = String(rawName)
        .replaceAll("_", " ")
        .replace(/\b\w/g, (character) => character.toUpperCase());
      const weakestScore = normalizeScore(typeof weakestRaw === "object" ? weakestRaw.similarity ?? weakestRaw.score : null);
      state.remoteLearning = {
        ...(state.remoteLearning || {}),
        weakest: {
          label,
          detail: weakestScore == null ? "Agent-selected attention joint" : `${Math.round(weakestScore * 100)}% aligned · server diagnosis`,
        },
      };
      normalizedWeakest = { raw: String(rawName), label, score: weakestScore };
    }
  }

  const memoryObject = nested.memory && typeof nested.memory === "object" ? nested.memory : {};
  const memoryEvents = Array.isArray(nested.session_memory)
    ? nested.session_memory
    : Array.isArray(memoryObject.events)
      ? memoryObject.events
      : Array.isArray(backendState.memory)
        ? backendState.memory
        : [];
  const memoryCount = Number(nested.memory_count ?? memoryObject.signal_count ?? backendState.memory_count);
  const jointEma = nested.joint_ema ?? memoryObject.joint_ema ?? {};
  const remoteMemories = [];
  if (normalizedWeakest) {
    const rollingScore = normalizeScore(jointEma[normalizedWeakest.raw] ?? normalizedWeakest.score);
    if (rollingScore != null && state.remoteLearning?.weakest) {
      state.remoteLearning.weakest.detail = `${Math.round(rollingScore * 100)}% rolling alignment · server diagnosis`;
    }
    remoteMemories.push({
      title: `${normalizedWeakest.label} is the current weak point`,
      detail: Number.isFinite(memoryCount) ? `${memoryCount} observed frame signals · rolling pattern` : "Rolling pose pattern",
      score: rollingScore == null ? "tracked" : `${Math.round(rollingScore * 100)}%`,
    });
  }
  memoryEvents.slice(-2).forEach((event, index) => {
    if (typeof event === "string") {
      remoteMemories.push({ title: event, detail: "Server session memory", score: "saved" });
      return;
    }
    const loop = event.loop ?? event.loop_id ?? index + 1;
    remoteMemories.push({
      title: event.title ?? `Loop ${loop} updated the coaching policy`,
      detail: event.detail ?? event.reason ?? event.event ?? (event.qualified ? "Mastery gate passed" : "Agent retained the current speed"),
      score: event.score ?? (event.policy_version ? `v${event.policy_version}` : "saved"),
    });
  });
  if (remoteMemories.length || Number.isFinite(memoryCount)) {
    state.memories = remoteMemories.slice(-3);
    state.remoteLearning = {
      ...(state.remoteLearning || {}),
      memories: state.memories,
      memoryCount: Number.isFinite(memoryCount) ? memoryCount : state.memories.length,
    };
    renderMemories();
  }

  const latency = Number(nested.latency_ms ?? nested.inference_ms);
  if (Number.isFinite(latency)) elements.latencyLabel.textContent = `Pose · ${Math.round(latency)} ms · 20 FPS target`;
  else if (source === "ws" && state.lastSocketSentAt) elements.latencyLabel.textContent = `Round trip · ${Math.round(performance.now() - state.lastSocketSentAt)} ms · 20 FPS target`;
}

async function fetchJson(path, options = {}, timeoutMs = 2400) {
  const controller = new AbortController();
  const timeout = window.setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(`${API_ORIGIN}${path}`, {
      ...options,
      headers: { "Content-Type": "application/json", Accept: "application/json", ...(options.headers || {}) },
      signal: controller.signal,
    });
    if (!response.ok) throw new Error(`Request failed (${response.status})`);
    const text = await response.text();
    return text ? JSON.parse(text) : {};
  } finally {
    window.clearTimeout(timeout);
  }
}

async function ensureSession(routineUrl = elements.routineUrl.value.trim()) {
  if (state.sessionId) return state.sessionId;
  if (state.sessionRequest) return state.sessionRequest;
  const localId = `local-${Date.now().toString(36)}`;
  state.sessionRequest = fetchJson("/api/sessions", {
    method: "POST",
    body: JSON.stringify({
      routine_url: routineUrl || null,
      mode: state.focus,
      practice_mode: state.mode,
      focus: state.focus,
      privacy: { store_frames: false, memory_scope: "session" },
      client: "tempodance-static-spa",
    }),
  })
    .then((payload) => {
      const nested = payload?.data ?? payload?.session ?? payload;
      state.sessionId = nested.session_id ?? nested.id ?? payload.session_id ?? payload.id ?? localId;
      state.remoteSession = state.sessionId !== localId;
      applyBackendPayload(payload);
      setConnection(state.remoteSession ? "connected" : "demo");
      return state.sessionId;
    })
    .catch(() => {
      state.sessionId = localId;
      state.remoteSession = false;
      setConnection("demo");
      return localId;
    })
    .finally(() => { state.sessionRequest = null; });
  return state.sessionRequest;
}

async function postObservation() {
  if (!state.remoteSession || !state.sessionId || !Number.isFinite(state.score) || state.observationInFlight) return;
  state.observationInFlight = true;
  const payload = {
    mode: state.mode,
    count: state.currentCount,
    speed: SPEEDS[state.speedIndex],
    focus: state.focus,
    score: state.score,
    bone_scores: state.boneScores,
    reference_keypoints: state.latestReference,
    user_keypoints: state.latestLive,
    timing_offset_ms: state.timingOffset,
    loop_id: state.completedLoops + 1,
    loop_progress: state.countPhase,
    frame_index: Math.floor(state.elapsedPlayingMs / 150),
    ephemeral: true,
  };
  try {
    const response = await fetchJson(`/api/sessions/${encodeURIComponent(state.sessionId)}/observe`, {
      method: "POST",
      body: JSON.stringify(payload),
    }, 1100);
    applyBackendPayload(response);
  } catch {
    // Observation is additive. Local coaching remains fully functional if it fails.
  } finally {
    state.observationInFlight = false;
  }
}

function connectSocket() {
  if (state.socket && [WebSocket.OPEN, WebSocket.CONNECTING].includes(state.socket.readyState)) return;
  setConnection("connecting");
  try {
    const socket = new WebSocket(`${WS_ORIGIN}/ws/pose`);
    state.socket = socket;
    socket.addEventListener("open", () => {
      state.socketReady = true;
      state.socketReconnects = 0;
      setConnection("connected");
      elements.liveBadge.innerHTML = "<i></i> Pose live";
    });
    socket.addEventListener("message", (event) => {
      try {
        applyBackendPayload(JSON.parse(event.data), "ws");
      } catch {
        // Ignore malformed optional telemetry; the next frame can recover.
      }
    });
    socket.addEventListener("close", () => {
      state.socketReady = false;
      if (state.mode !== "camera" || !state.cameraReady) return;
      setConnection("error");
      if (state.socketReconnects < 2) {
        state.socketReconnects += 1;
        window.setTimeout(connectSocket, 750 * state.socketReconnects);
      } else {
        showBanner("Pose service is offline. This interface does not save the frame; switch to Demo mode for the full coaching flow.");
      }
    });
    socket.addEventListener("error", () => {
      state.socketReady = false;
    });
  } catch {
    setConnection("error");
  }
}

function sendCameraFrame(now) {
  if (!state.cameraReady || !state.socketReady || !state.playing || now - state.lastSocketSentAt < 50) return;
  if (state.socket.bufferedAmount > 350_000) return;
  const video = elements.cameraVideo;
  if (!video.videoWidth || !video.videoHeight) return;
  const canvas = elements.captureCanvas;
  const targetWidth = 480;
  const targetHeight = Math.round(targetWidth * video.videoHeight / video.videoWidth);
  canvas.width = targetWidth;
  canvas.height = targetHeight;
  const ctx = canvas.getContext("2d", { alpha: false });
  ctx.drawImage(video, 0, 0, targetWidth, targetHeight);
  const image = canvas.toDataURL("image/jpeg", .68);
  const message = {
    image,
    reference_keypoints: state.latestReference,
    focus: state.focus,
    session_id: state.sessionId,
  };
  state.lastSocketSentAt = now;
  try {
    state.socket.send(JSON.stringify(message));
  } catch {
    // A close event handles recovery.
  }
}

function setConnection(kind) {
  elements.connectionDot.className = "connection-dot";
  if (kind === "connecting") {
    elements.connectionDot.classList.add("connecting");
    elements.connectionLabel.textContent = "Connecting pose engine";
  } else if (kind === "connected") {
    elements.connectionLabel.textContent = state.mode === "camera" ? "Pose engine connected" : "Agent session connected";
  } else if (kind === "error") {
    elements.connectionDot.classList.add("error");
    elements.connectionLabel.textContent = "Service unavailable";
  } else {
    elements.connectionLabel.textContent = "Demo engine ready";
  }
}

function extractYouTubeVideoId(url) {
  try {
    const parsed = new URL(url);
    if (parsed.hostname === "youtu.be") return parsed.pathname.split("/").filter(Boolean)[0] || null;
    if (parsed.hostname.endsWith("youtube.com")) {
      if (parsed.pathname.startsWith("/shorts/") || parsed.pathname.startsWith("/embed/")) {
        return parsed.pathname.split("/").filter(Boolean)[1] || null;
      }
      return parsed.searchParams.get("v");
    }
  } catch {
    return null;
  }
  return null;
}

async function analyzeRoutine() {
  if (state.analyzing) return;
  const url = elements.routineUrl.value.trim();
  try {
    const parsed = new URL(url);
    if (!/^https?:$/.test(parsed.protocol)) throw new Error();
  } catch {
    showBanner("Paste a valid YouTube URL.");
    elements.routineUrl.focus();
    return;
  }
  if (extractYouTubeVideoId(url) !== SOURCE_VIDEO_ID) {
    showBanner(`This build packages ${SOURCE_VIDEO_ID}. Run scripts/process_tutorial.py to generate local video and pose assets for a different tutorial.`);
    elements.routineUrl.focus();
    return;
  }

  state.analyzing = true;
  state.sessionId = null;
  state.remoteSession = false;
  elements.analyzeButton.classList.add("loading");
  elements.analyzeButton.disabled = true;
  elements.referenceLoading.hidden = false;
  elements.analyzeButton.querySelector(".button-label").textContent = "Preparing";
  setConnection("connecting");
  pausePractice();

  const started = performance.now();
  await ensureSession(url);
  const remaining = 950 - (performance.now() - started);
  if (remaining > 0) await new Promise((resolve) => window.setTimeout(resolve, remaining));

  elements.referenceVideo.pause();
  elements.referenceVideo.currentTime = 0;
  state.phase = 0;
  state.previousSourceTime = 0;
  elements.routineName.textContent = "Hollywood Action · mirrored tutorial";
  elements.routineBpm.textContent = String(Math.round(state.detectedBpm));
  elements.referenceLoading.hidden = true;
  elements.analyzeButton.classList.remove("loading");
  elements.analyzeButton.disabled = false;
  elements.analyzeButton.querySelector(".button-label").textContent = "Prepared";
  state.analyzing = false;
  toast(state.remoteSession ? "Local video, audio, and ML pose track ready" : "Local source and ML pose track ready · backend optional");
}

async function setMode(mode) {
  if (mode === state.mode) return;
  pausePractice();
  state.mode = mode;
  if (mode === "demo" && state.cameraStream) stopCamera();
  state.serverPose = null;
  state.latestLive = null;
  state.score = null;
  state.boneScores = {};
  updateScoreUI();
  elements.demoModeButton.classList.toggle("active", mode === "demo");
  elements.demoModeButton.setAttribute("aria-pressed", String(mode === "demo"));
  elements.cameraModeButton.classList.toggle("active", mode === "camera");
  elements.cameraModeButton.setAttribute("aria-pressed", String(mode === "camera"));
  elements.cameraEmpty.hidden = mode !== "camera" || state.cameraReady;
  elements.cameraError.hidden = true;
  elements.cameraVideo.hidden = mode !== "camera" || !state.cameraReady;
  elements.livePanelTitle.textContent = mode === "demo" ? "Deterministic dancer" : "Your movement";
  elements.liveBadge.innerHTML = mode === "demo" ? "<i></i> Ready" : "<i></i> Camera off";
  elements.latencyLabel.textContent = mode === "demo" ? "Local simulation · 0 ms" : "Waiting for camera";
  elements.timingMetric.textContent = "--";
  elements.timingDelta.textContent = "Video, audio, and overlay share one clock";
  setConnection(mode === "demo" ? "demo" : "connecting");
  if (mode === "camera" && state.cameraReady) connectSocket();
}

async function enableCamera() {
  elements.cameraEmpty.hidden = true;
  elements.cameraError.hidden = true;
  elements.liveBadge.innerHTML = "<i></i> Requesting";
  try {
    if (!navigator.mediaDevices?.getUserMedia) throw new Error("This browser does not expose camera access.");
    const stream = await navigator.mediaDevices.getUserMedia({
      video: {
        facingMode: "user",
        width: { ideal: 960 },
        height: { ideal: 720 },
        frameRate: { ideal: 30 },
      },
      audio: false,
    });
    state.cameraStream = stream;
    state.cameraReady = true;
    elements.cameraVideo.srcObject = stream;
    await elements.cameraVideo.play();
    elements.cameraVideo.hidden = false;
    elements.liveBadge.innerHTML = "<i></i> Camera ready";
    elements.latencyLabel.textContent = "Camera 30 FPS · pose target 20 FPS";
    await ensureSession();
    connectSocket();
    toast("Camera enabled · frames remain ephemeral");
  } catch (error) {
    state.cameraReady = false;
    elements.cameraError.hidden = false;
    elements.cameraErrorText.textContent = error?.name === "NotAllowedError"
      ? "Camera permission was declined. You can change it in browser settings or use the full Demo mode."
      : `${error?.message || "Camera could not start."} Demo mode remains available.`;
    elements.liveBadge.innerHTML = "<i></i> Unavailable";
    setConnection("error");
  }
}

function stopCamera() {
  state.cameraStream?.getTracks().forEach((track) => track.stop());
  state.cameraStream = null;
  state.cameraReady = false;
  elements.cameraVideo.srcObject = null;
  elements.cameraVideo.hidden = true;
  if (state.socket) state.socket.close(1000, "Session ended");
  state.socket = null;
  state.socketReady = false;
}

async function startPractice() {
  if (state.analyzing) return;
  if (state.mode === "camera" && !state.cameraReady) {
    await enableCamera();
    if (!state.cameraReady) return;
  }
  ensureSession();
  elements.referenceVideo.playbackRate = SPEEDS[state.speedIndex];
  elements.referenceVideo.muted = !state.audioEnabled;
  elements.referenceVideo.volume = 1;
  try {
    await elements.referenceVideo.play();
  } catch {
    showBanner("The browser blocked video playback. Press play again to allow the tutorial audio.");
    return;
  }
  state.playing = true;
  state.sessionStartedAt ??= Date.now();
  state.lastFrameAt = performance.now();
  elements.playButton.classList.add("playing");
  elements.playButton.setAttribute("aria-label", "Pause practice");
  elements.transportTitle.textContent = `Loop ${state.completedLoops + 1} · count ${state.currentCount}`;
  elements.transportHint.textContent = `Follow only the ${state.focus === "full" ? "combined move" : `${state.focus}-body overlay`} with the source audio.`;
  if (state.mode === "camera") connectSocket();
}

function pausePractice() {
  state.playing = false;
  elements.referenceVideo.pause();
  elements.playButton.classList.remove("playing");
  elements.playButton.setAttribute("aria-label", "Start practice");
  if (Number.isFinite(state.score)) {
    elements.transportTitle.textContent = `Paused on count ${state.currentCount}`;
    elements.transportHint.textContent = "Your visible session state is held until you resume or end this run.";
  }
}

function resetSession({ keepMode = true } = {}) {
  pausePractice();
  stopCamera();
  elements.referenceVideo.currentTime = 0;
  Object.assign(state, {
    mode: keepMode ? state.mode : "demo",
    practicePlan: "steps",
    focus: "upper",
    phase: 0,
    countPhase: 0,
    currentCount: 1,
    currentBeatIndex: -1,
    completedLoops: 0,
    cleanLoops: 0,
    loopMinimum: 1,
    elapsedPlayingMs: 0,
    sessionStartedAt: null,
    sessionId: null,
    remoteSession: false,
    score: null,
    boneScores: {},
    latestLive: null,
    serverPose: null,
    timingOffset: null,
    chartScores: [],
    memories: [],
    policyVersion: 1,
    remoteCoaching: null,
    remoteLearning: null,
    observationInFlight: false,
    speedIndex: 0,
    previousSourceTime: 0,
  });
  elements.cleanLoops.textContent = "0";
  elements.sessionClock.textContent = "00:00";
  elements.timingMetric.textContent = "Ready";
  elements.transportTitle.textContent = "Ready for your first loop";
  elements.transportHint.textContent = "Press play — the coach will adapt after each pass.";
  elements.coachCue.hidden = false;
  elements.policyVersion.textContent = "Policy v1.0";
  elements.policyRule.innerHTML = "<b>Baseline:</b> scan full body equally.";
  elements.chartLine.setAttribute("d", "");
  elements.chartArea.setAttribute("d", "");
  renderMemories();
  updateSpeedUI();
  updateScoreUI();
  updateCountUI();
  setFocus("upper", { announce: false });
  if (!keepMode) {
    elements.demoModeButton.classList.add("active");
    elements.demoModeButton.setAttribute("aria-pressed", "true");
    elements.cameraModeButton.classList.remove("active");
    elements.cameraModeButton.setAttribute("aria-pressed", "false");
    elements.cameraEmpty.hidden = true;
    elements.cameraError.hidden = true;
    elements.livePanelTitle.textContent = "Deterministic dancer";
    elements.liveBadge.innerHTML = "<i></i> Ready";
    elements.latencyLabel.textContent = "Local simulation · 0 ms";
  }
  setConnection("demo");
  if (state.mode === "camera") setMode("demo");
}

function showBanner(message) {
  elements.statusBannerText.textContent = message;
  elements.statusBanner.hidden = false;
}

function toast(message, type = "success") {
  const item = document.createElement("div");
  item.className = `toast ${type === "error" ? "error" : ""}`;
  const dot = document.createElement("i");
  const text = document.createElement("span");
  text.textContent = message;
  item.append(dot, text);
  elements.toastRegion.append(item);
  window.setTimeout(() => item.remove(), 3600);
}

function tick(now) {
  const delta = Math.min(now - state.lastFrameAt, 100);
  state.lastFrameAt = now;

  if (state.playing) {
    state.elapsedPlayingMs += delta;
    const speed = SPEEDS[state.speedIndex];
    const previousPhase = state.phase;
    const sourceDuration = elements.referenceVideo.duration || state.sourceDuration;
    if (elements.referenceVideo.readyState >= HTMLMediaElement.HAVE_CURRENT_DATA && sourceDuration > 0) {
      const sourceTime = elements.referenceVideo.currentTime;
      state.phase = clamp(sourceTime / sourceDuration);
      if (sourceTime + .25 < state.previousSourceTime) state.currentBeatIndex = -1;
      if (state.sourceBeats.length) {
        const beatIndex = state.sourceBeats.findLastIndex((beat) => beat <= sourceTime + .015);
        if (beatIndex >= 0) {
          const previousBeatIndex = state.currentBeatIndex;
          const beatStart = state.sourceBeats[beatIndex];
          const beatEnd = state.sourceBeats[beatIndex + 1] ?? beatStart + 60 / state.detectedBpm;
          const beatProgress = clamp((sourceTime - beatStart) / (beatEnd - beatStart));
          state.currentCount = (beatIndex % 8) + 1;
          state.countPhase = ((beatIndex % 8) + beatProgress) / 8;
          if (previousBeatIndex >= 0 && Math.floor(beatIndex / 8) > Math.floor(previousBeatIndex / 8)) handleCompletedLoop();
          state.currentBeatIndex = beatIndex;
        } else {
          state.currentCount = 1;
          state.countPhase = 0;
        }
      } else {
        state.currentCount = Math.min(8, Math.floor(state.phase * 8) + 1);
        state.countPhase = state.phase;
      }
      state.previousSourceTime = sourceTime;
    } else {
      const loopDuration = (state.sourceDuration * 1000) / speed;
      state.phase = (state.phase + delta / loopDuration) % 1;
      if (state.phase < previousPhase) handleCompletedLoop();
      state.currentCount = Math.min(8, Math.floor(state.phase * 8) + 1);
      state.countPhase = state.phase;
    }
    state.loopMinimum = Math.min(state.loopMinimum, state.score ?? 1);
    elements.transportTitle.textContent = `Loop ${state.completedLoops + 1} · count ${state.currentCount}`;
    elements.sessionClock.textContent = formatTime(state.elapsedPlayingMs);
  }

  if (!state.sourceMotionReady) {
    clearCanvas(elements.referenceCanvas);
    clearCanvas(elements.liveCanvas);
    updateCountUI();
    updateTimingUI();
    requestAnimationFrame(tick);
    return;
  }

  state.latestReference = getReferencePose(state.phase);
  const trailOffset = 1 / state.routineKeyframes.length;
  const trailReference = getReferencePose((state.phase - trailOffset + 1) % 1);
  renderSkeleton(elements.referenceCanvas, state.latestReference, {
    primary: "#a98aff",
    trailPose: trailReference,
    focus: state.focus,
    sourceAspect: SOURCE_ASPECT_RATIO,
  });

  if (state.mode === "demo") {
    state.latestLive = createDemoPose(state.latestReference, now);
    const learningPenalty = state.playing ? lerp(.075, .008, clamp(state.elapsedPlayingMs / 7000)) : .075;
    const result = calculatePoseScore(state.latestLive, state.latestReference, learningPenalty);
    state.score = state.playing ? result.score : state.score;
    state.boneScores = result.boneScores;
    renderSkeleton(elements.liveCanvas, state.latestLive, {
      primary: "#b7ff5a",
      feedback: true,
      boneScores: state.boneScores,
      trailPose: createDemoPose(getReferencePose((state.phase - trailOffset + 1) % 1), now - 35),
      focus: state.focus,
    });
  } else if (state.serverPose) {
    state.latestLive = state.serverPose;
    if (!Number.isFinite(state.score) || !Object.keys(state.boneScores).length) {
      const localResult = calculatePoseScore(state.serverPose, state.latestReference);
      state.score = localResult.score;
      state.boneScores = localResult.boneScores;
    }
    renderSkeleton(elements.liveCanvas, state.serverPose, { primary: "#b7ff5a", feedback: true, boneScores: state.boneScores, focus: state.focus });
  } else {
    clearCanvas(elements.liveCanvas);
  }

  updateCountUI();
  updateScoreUI();
  updateTimingUI(now);
  updateAgentUI();
  updateChart(now);

  if (state.playing && now - state.lastObservationAt > 150) {
    state.lastObservationAt = now;
    postObservation();
  }
  if (state.mode === "camera") sendCameraFrame(now);
  requestAnimationFrame(tick);
}

function initialize() {
  const markers = $("#countMarkers");
  for (let index = 1; index <= 8; index += 1) {
    const marker = document.createElement("i");
    marker.className = "count-marker";
    marker.dataset.count = index;
    markers.append(marker);
  }

  elements.playButton.addEventListener("click", () => state.playing ? pausePractice() : startPractice());
  elements.analyzeButton.addEventListener("click", analyzeRoutine);
  elements.routineUrl.addEventListener("keydown", (event) => {
    if (event.key === "Enter") analyzeRoutine();
  });
  elements.demoModeButton.addEventListener("click", () => setMode("demo"));
  elements.cameraModeButton.addEventListener("click", () => setMode("camera"));
  elements.enableCameraButton.addEventListener("click", enableCamera);
  elements.useDemoFallbackButton.addEventListener("click", () => setMode("demo"));
  elements.audioToggle.addEventListener("click", () => setAudioEnabled(!state.audioEnabled));
  elements.stepPlanButton.addEventListener("click", () => setPracticePlan("steps"));
  elements.fullPlanButton.addEventListener("click", () => setPracticePlan("full"));
  $$(".focus-step").forEach((button) => {
    button.addEventListener("click", () => setFocus(button.dataset.focus));
  });
  elements.nextFocusButton.addEventListener("click", () => {
    const index = FOCUS_STEPS.findIndex((step) => step.id === state.focus);
    setFocus(FOCUS_STEPS[(index + 1) % FOCUS_STEPS.length].id);
  });
  $$(".speed-tier").forEach((button, index) => {
    button.addEventListener("click", () => {
      const wasHigher = index > state.speedIndex;
      state.speedIndex = index;
      state.cleanLoops = 0;
      elements.referenceVideo.playbackRate = SPEEDS[index];
      elements.cleanLoops.textContent = "0";
      updateSpeedUI();
      toast(wasHigher ? `Manual control · speed set to ${formatPlaybackSpeed(SPEEDS[index])}` : `Coach speed set to ${formatPlaybackSpeed(SPEEDS[index])}`);
    });
  });
  $("#privacyButton").addEventListener("click", () => {
    if (typeof elements.privacyDialog.showModal === "function") elements.privacyDialog.showModal();
    else elements.privacyDialog.setAttribute("open", "");
  });
  $("#endSessionButton").addEventListener("click", () => {
    resetSession({ keepMode: false });
    toast("Browser session cleared · camera and connection closed; server memory lasts until restart");
  });
  $("#dismissBanner").addEventListener("click", () => { elements.statusBanner.hidden = true; });
  window.addEventListener("beforeunload", stopCamera);
  window.addEventListener("resize", () => {
    // Canvas dimensions are refreshed by the next animation frame.
  }, { passive: true });

  renderMemories();
  elements.referenceVideo.loop = true;
  elements.referenceVideo.preservesPitch = true;
  elements.referenceVideo.playbackRate = SPEEDS[state.speedIndex];
  setAudioEnabled(true, { announce: false });
  elements.referenceVideo.addEventListener("error", () => {
    showBanner("The packaged tutorial video could not load. Re-run scripts/process_tutorial.py to restore it.");
  });
  elements.referenceVideo.addEventListener("loadedmetadata", () => {
    state.sourceDuration = elements.referenceVideo.duration || state.sourceDuration;
  });
  loadSourceMotion();
  setFocus("upper", { announce: false });
  updateCountUI();
  requestAnimationFrame(tick);
}

initialize();
